(defparameter eax #x69E)
(defparameter rd9 #xBD)

(defun test(str)
	(let ((len (length str))
				(ebx 0)
				(edx 0)
				(ecx 0))
		(loop for i from 0 to (- len 1)
					do (setf ecx (char-code (char str i)))
					do (setf ecx (logxor ecx edx))
				 	do (setf edx (1+ edx))
					do (setf ecx (logxor ecx rd9))
					do (setf ebx (+ ebx ecx)))
		(progn
			(setf ecx #xA)
			(setf ecx (logxor ecx edx))
			(setf ecx (logxor ecx rd9))
			(setf ebx (+ ebx ecx))
			(format t "~X~%" ebx))))
